### ISSUE TITLE
Implement filtering in Movement and Workout lists

### ISSUE THREAD

**Issue by egilsster** [egilsster/wodbook-app#5]
The search bar should be a header of the `FlatList` element

**Comment by mauscoelho** [comment]
Can I use SearchBar from [react-native-elements](https://react-native-training.github.io/react-native-elements/docs/searchbar.html) or do you prefer an own component?

**Comment by mauscoelho** [comment]
I took a look that is already implemented the functionality in branch `searching`, what is missing to finish?

**Comment by egilsster** [comment]
@mauscoelho I took an initial stab at this using the `Search` component from `react-native-elements`, however, I am not happy with how it works and looks so I have been looking into using the `Search` component from `react-native-ios-kit` instead. The problem I hit was that since I am using `react-native-navigation`, I can not wrap the root component with a `ThemeProvider` (which ios-kit requires from what I could work out) so it crashes. I did try a method of wrapping all the screens with the same provider but I lost the `navigation` from the components so when I clicked something to go to a new view, it would crash.

I have not taken a really deep dive into the issue or figuring out workarounds so I have not wrapped up the PR for this work. I opened a WIP PR where I will document this as well and will push the changes I have done with `react-native-ios-kit`.

**Comment by mauscoelho** [comment]
I created the PR #20 to fix the problem with navigation, is there anything more to contribute to this issue?

**Comment by egilsster** [comment]
Thank you so much for the PR, really appreciate it!

> about `react-native-ios-kit`, this app will work only on iOS?

This is honestly a part I did not realize. The plan is to support both platforms so I am going to revert the change of libraries (or go with something totally different) and make some changes to what I had before.

I am going to merge your PR into my branch because I think for the time being it is good to keep the wrapping functionality for the screens but it might be chucked later down the road since things might change with `react-native-navigation` v2. I am still learning a lot of new things in both React and React-Native so I will likely swap things fairly quickly and experiment with things.

**Comment by mauscoelho** [comment]
I am still learning TypeScript too and I've never used `react-native-navigation`. I know [react-navigation](https://reactnavigation.org). But this `react-native-navigation` looks work very well :)

How can I help to finalize this functionality?

**Comment by egilsster** [comment]
It is almost done right now. One issue I would like to fix, maybe you can take a look at it; if I enter something into the search box I have to tap twice on an item, or even the clear icon for something to happen. I would like it to be just a single tap. Also, less of an issue but more a preference, if I could extract the SearchBar component into its own file and skin style it there and use that in both the `MovementList` and `WorkoutList` views, lots of duplication, even though `onChange`, `onClear` and maybe `value` and `clearIcon` would still need to be passed in. Going to leave the PR open for now.

Here is how it looks:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/5672257/39150714-c24dc9d6-4732-11e8-8143-ccb7f28cf0b7.png">

**Comment by egilsster** [comment]
Closes by #19
